### ISSUE TITLE
Clarity around Node JS vs client side

### ISSUE THREAD

**Issue by SteveBarnett** [codex-academy/geolib-experiments#1]
Do we need some clarity here? I got confused about whether we were in Node land or browser land.

Maybe we should add a bit in **Use app.js** that says "If you want to use geolib in the browser, you can use this example app.js." ?

**Comment by avermeulen** [comment]
I did add a section about it. In the readme file doesn't it make sense wgat
I wrote in the readme?

**Comment by SteveBarnett** [comment]
Not quite clear, for me. I'll submit a PR with what I mean. :)

**Comment by avermeulen** [comment]
Thanks!
